nodes:
  retrieve-timeout: 5
  exit-timeout: 30
db:
  migrations:
    folder: "file://migrations"
    connectionString: "postgresql://postgres:1@gluten-db:5432/gluten?sslmode=disable"
    enable: true
  connection:
    url: "host=gluten-db user=postgres dbname=gluten sslmode=disable password=1"