// Code generated by protoc-gen-go.
// source: protoService.proto
// DO NOT EDIT!

/*
Package proto_service is a generated protocol buffer package.

It is generated from these files:
	protoService.proto

It has these top-level messages:
	ParamsRequest
	ReplyMessage
*/
package proto_service

import proto "github.com/golang/protobuf/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type ParamsRequest struct {
	Url  string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Body string `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
}

func (m *ParamsRequest) Reset()         { *m = ParamsRequest{} }
func (m *ParamsRequest) String() string { return proto.CompactTextString(m) }
func (*ParamsRequest) ProtoMessage()    {}

type ReplyMessage struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *ReplyMessage) Reset()         { *m = ReplyMessage{} }
func (m *ReplyMessage) String() string { return proto.CompactTextString(m) }
func (*ReplyMessage) ProtoMessage()    {}

func init() {
	proto.RegisterType((*ParamsRequest)(nil), "proto_service.ParamsRequest")
	proto.RegisterType((*ReplyMessage)(nil), "proto_service.ReplyMessage")
}

// Client API for ProtoService service

type ProtoServiceClient interface {
	SendConfig(ctx context.Context, in *ParamsRequest, opts ...grpc.CallOption) (*ReplyMessage, error)
}

type protoServiceClient struct {
	cc *grpc.ClientConn
}

func NewProtoServiceClient(cc *grpc.ClientConn) ProtoServiceClient {
	return &protoServiceClient{cc}
}

func (c *protoServiceClient) SendConfig(ctx context.Context, in *ParamsRequest, opts ...grpc.CallOption) (*ReplyMessage, error) {
	out := new(ReplyMessage)
	err := grpc.Invoke(ctx, "/proto_service.ProtoService/SendConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProtoService service

type ProtoServiceServer interface {
	SendConfig(context.Context, *ParamsRequest) (*ReplyMessage, error)
}

func RegisterProtoServiceServer(s *grpc.Server, srv ProtoServiceServer) {
	s.RegisterService(&_ProtoService_serviceDesc, srv)
}

func _ProtoService_SendConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoServiceServer).SendConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_service.ProtoService/SendConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoServiceServer).SendConfig(ctx, req.(*ParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProtoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto_service.ProtoService",
	HandlerType: (*ProtoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendConfig",
			Handler:    _ProtoService_SendConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}
