CREATE TABLE execution(
  id VARCHAR(255) PRIMARY KEY NOT NULL,
  created BIGINT NOT NULL,
  status VARCHAR(255) NOT NULL
);

CREATE TABLE execution_result(
  id VARCHAR(255) PRIMARY KEY NOT NULL,
  created BIGINT NOT NULL,
  step_type VARCHAR(255) NOT null,
  execution_id VARCHAR(255) NOT NULL REFERENCES execution(id)
  ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE metric(
  key VARCHAR(100) NOT NULL,
  value VARCHAR(100) NOT NULL,
  result_id VARCHAR(255) NOT NULL REFERENCES execution_result(id)
  ON UPDATE CASCADE ON DELETE CASCADE
);